spring:
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  cloud:
    discovery:
      enabled: false
  mail:
    host: localhost
    port: 2525

eureka:
  client:
    enabled: false
