package com.fd.events;

public enum PaymentStatus {
	PAYMENT_CREATED,
	PAYMENT_INITIATED,
	PAYMENT_PENDING,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REFUND_INITIATED,
    REFUND_SUCCESS,
    REFUND_FAILED
}
